source 'https://github.com/lyleLH/MTSpecs.git'
source 'https://cdn.cocoapods.org/'                  #官方仓库地址 cdn
 
#use_frameworks!

platform :ios, '9.0'

target 'DGMapModule_Example' do
  pod 'DGMapModule', :path => '../'
  pod 'LookinServer', :configurations => ['Debug']
  target 'DGMapModule_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
