use_frameworks!

platform :ios, '9.0'

target 'DGMapModule_Example' do
  pod 'DGMapModule', :path => '../'

  target 'DGMapModule_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
